docker exec -i xzhou13 ps -ef | grep sssd |wc -l
docker exec -i lyu15 ps -ef | grep sssd |wc -l
docker exec -i jyoder5 ps -ef | grep sssd |wc -l
docker exec -i hwk643 ps -ef | grep sssd |wc -l
docker exec -i avalesky ps -ef | grep sssd |wc -l
docker exec -i pvaccaro ps -ef | grep sssd |wc -l
docker exec -i jtolen ps -ef | grep sssd |wc -l
docker exec -i tstuessi ps -ef | grep sssd |wc -l
docker exec -i ssoleman ps -ef | grep sssd |wc -l
docker exec -i pshires1 ps -ef | grep sssd |wc -l
docker exec -i tshield7 ps -ef | grep sssd |wc -l
docker exec -i mschmid3 ps -ef | grep sssd |wc -l
docker exec -i sschaff1 ps -ef | grep sssd |wc -l
docker exec -i ksayarat ps -ef | grep sssd |wc -l
docker exec -i srichmo1 ps -ef | grep sssd |wc -l
docker exec -i jreyno40 ps -ef | grep sssd |wc -l
docker exec -i srausch ps -ef | grep sssd |wc -l
docker exec -i jqiu1 ps -ef | grep sssd |wc -l
docker exec -i eoffor ps -ef | grep sssd |wc -l
docker exec -i jnguye11 ps -ef | grep sssd |wc -l
docker exec -i jmuhamm1 ps -ef | grep sssd |wc -l
docker exec -i jmoscato ps -ef | grep sssd |wc -l
docker exec -i cmennen ps -ef | grep sssd |wc -l
docker exec -i smcnally ps -ef | grep sssd |wc -l
docker exec -i pmcknig1 ps -ef | grep sssd |wc -l
docker exec -i dmaster1 ps -ef | grep sssd |wc -l
docker exec -i tmarsha9 ps -ef | grep sssd |wc -l
docker exec -i wmacey ps -ef | grep sssd |wc -l
docker exec -i hkoditu1 ps -ef | grep sssd |wc -l
docker exec -i ikanter ps -ef | grep sssd |wc -l
docker exec -i ajusino ps -ef | grep sssd |wc -l
docker exec -i cjohn221 ps -ef | grep sssd |wc -l
docker exec -i jholla19 ps -ef | grep sssd |wc -l
docker exec -i thobson2 ps -ef | grep sssd |wc -l
docker exec -i ghannah ps -ef | grep sssd |wc -l
docker exec -i mgepner ps -ef | grep sssd |wc -l
docker exec -i kgaboure ps -ef | grep sssd |wc -l
docker exec -i jdiamon3 ps -ef | grep sssd |wc -l
docker exec -i kmccoy4 ps -ef | grep sssd |wc -l
docker exec -i bdenton4 ps -ef | grep sssd |wc -l
docker exec -i adeitz1 ps -ef | grep sssd |wc -l
docker exec -i ccraig7 ps -ef | grep sssd |wc -l
docker exec -i kchiang ps -ef | grep sssd |wc -l
docker exec -i tchen21 ps -ef | grep sssd |wc -l
docker exec -i mcauthen ps -ef | grep sssd |wc -l
docker exec -i kbrown42 ps -ef | grep sssd |wc -l
docker exec -i dandersh ps -ef | grep sssd |wc -l
