#!/usr/bin/bash

#Script to setup VM

apt update && apt -y upgrade

groupadd -r mongodb && useradd -r -g mongodb mongodb

apt update && DEBIAN_FRONTEND='noninteractive' apt install -y wget curl gnupg apt-transport-https
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
apt update
apt install -y mongodb-org-shell mongodb-org-server \
    mongodb-org-tools mongodb-org-mongos \
    libssl-dev \
    libcurl4-openssl-dev \
    openssh-server \
    lsof sudo \
    vim \
    git \
    curl lsb-release \
    vim-runtime tmux zsh zip \
    python3-pymongo python3-requests
    
rm -rf /var/lib/apt/lists/*
rm -f /usr/local/bin/systemctl
rm -rf /var/lib/mongodb
mv /etc/mongod.conf /etc/mongod.conf.orig

mkdir -p /data/db /data/configdb \
	&& chown -R mongodb:mongodb /data/db /data/configdb

return 0 

