#!/usr/bin/bash

#Script to setup VM

#apt update && apt -y upgrade
#ln -s /bin/true /usr/local/bin/systemctl 
apt install -y mongodb-org-shell mongodb-org-server \
    mongodb-org-tools mongodb-org-mongos \
    libssl-dev \
    libcurl4-openssl-dev \
    openssh-server \
    lsof sudo \
    sssd \
    sssd-tools \
    vim \
    git \
    curl lsb-release \
    vim-runtime tmux zsh zip \
    python3-pymongo python3-requests
    
rm -rf /var/lib/apt/lists/*
rm -f /usr/local/bin/systemctl
rm -rf /var/lib/mongodb
mv /etc/mongod.conf /etc/mongod.conf.orig

mkdir -p /data/db /data/configdb \
	&& chown -R mongodb:mongodb /data/db /data/configdb

return 0 

